#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.
if [ -z "$(ps -ef | grep elasticsearch | grep -v grep)" ]
then
      client_result "elasticsearch is already stopped"
else
      kill `ps -ef | grep elasticsearch | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi

if [ -z "$(ps -ef | grep nginx | grep -v grep)" ]
then
      client_result "nginx is already stopped"
else
      kill `ps -ef | grep nginx | grep -v grep | awk '{ print $2 }'` > /dev/null 2>&1
fi
